[package]
name = "cnclient"
version = "0.1.0"
edition = "2021"

[dependencies]
cncommon = { version = "*", path = "../cncommon" }
cnbackend = { version = "*", path = "../cnbackend" }
cnlibfrontend = { version = "*", path = "../cnlibfrontend" }
